//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMovieRatingSystemClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movie", Namespace="http://schemas.datacontract.org/2004/07/OnlineMovieRatingSystem.Model")]
    [System.SerializableAttribute()]
    public partial class Movie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Movie_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Movie_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Movie_RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Movie_TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Movie_Id {
            get {
                return this.Movie_IdField;
            }
            set {
                if ((this.Movie_IdField.Equals(value) != true)) {
                    this.Movie_IdField = value;
                    this.RaisePropertyChanged("Movie_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Movie_Name {
            get {
                return this.Movie_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Movie_NameField, value) != true)) {
                    this.Movie_NameField = value;
                    this.RaisePropertyChanged("Movie_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Movie_Rating {
            get {
                return this.Movie_RatingField;
            }
            set {
                if ((this.Movie_RatingField.Equals(value) != true)) {
                    this.Movie_RatingField = value;
                    this.RaisePropertyChanged("Movie_Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Movie_Type {
            get {
                return this.Movie_TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Movie_TypeField, value) != true)) {
                    this.Movie_TypeField = value;
                    this.RaisePropertyChanged("Movie_Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemUser", Namespace="http://schemas.datacontract.org/2004/07/OnlineMovieRatingSystem.Model")]
    [System.SerializableAttribute()]
    public partial class SystemUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_DesignationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Designation {
            get {
                return this.User_DesignationField;
            }
            set {
                if ((object.ReferenceEquals(this.User_DesignationField, value) != true)) {
                    this.User_DesignationField = value;
                    this.RaisePropertyChanged("User_Designation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Name {
            get {
                return this.User_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.User_NameField, value) != true)) {
                    this.User_NameField = value;
                    this.RaisePropertyChanged("User_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Password {
            get {
                return this.User_PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.User_PasswordField, value) != true)) {
                    this.User_PasswordField = value;
                    this.RaisePropertyChanged("User_Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User_Rating", Namespace="http://schemas.datacontract.org/2004/07/OnlineMovieRatingSystem.Model")]
    [System.SerializableAttribute()]
    public partial class User_Rating : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MovieNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OnlineMovieRatingSystemClient.ServiceReference1.SystemUser SystemUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double User_Provided_RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_Rarting_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MovieName {
            get {
                return this.MovieNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieNameField, value) != true)) {
                    this.MovieNameField = value;
                    this.RaisePropertyChanged("MovieName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlineMovieRatingSystemClient.ServiceReference1.SystemUser SystemUser {
            get {
                return this.SystemUserField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemUserField, value) != true)) {
                    this.SystemUserField = value;
                    this.RaisePropertyChanged("SystemUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double User_Provided_Rating {
            get {
                return this.User_Provided_RatingField;
            }
            set {
                if ((this.User_Provided_RatingField.Equals(value) != true)) {
                    this.User_Provided_RatingField = value;
                    this.RaisePropertyChanged("User_Provided_Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Rarting_Id {
            get {
                return this.User_Rarting_IdField;
            }
            set {
                if ((this.User_Rarting_IdField.Equals(value) != true)) {
                    this.User_Rarting_IdField = value;
                    this.RaisePropertyChanged("User_Rarting_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RatinDto", Namespace="http://schemas.datacontract.org/2004/07/OnlineMovieRatingSystem.Model")]
    [System.SerializableAttribute()]
    public partial class RatinDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MovieNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double User_Provided_RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_Rarting_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MovieName {
            get {
                return this.MovieNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieNameField, value) != true)) {
                    this.MovieNameField = value;
                    this.RaisePropertyChanged("MovieName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double User_Provided_Rating {
            get {
                return this.User_Provided_RatingField;
            }
            set {
                if ((this.User_Provided_RatingField.Equals(value) != true)) {
                    this.User_Provided_RatingField = value;
                    this.RaisePropertyChanged("User_Provided_Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Rarting_Id {
            get {
                return this.User_Rarting_IdField;
            }
            set {
                if ((this.User_Rarting_IdField.Equals(value) != true)) {
                    this.User_Rarting_IdField = value;
                    this.RaisePropertyChanged("User_Rarting_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RatinDto2", Namespace="http://schemas.datacontract.org/2004/07/OnlineMovieRatingSystem.Model")]
    [System.SerializableAttribute()]
    public partial class RatinDto2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MovieNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double User_Provided_RatingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MovieName {
            get {
                return this.MovieNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieNameField, value) != true)) {
                    this.MovieNameField = value;
                    this.RaisePropertyChanged("MovieName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double User_Provided_Rating {
            get {
                return this.User_Provided_RatingField;
            }
            set {
                if ((this.User_Provided_RatingField.Equals(value) != true)) {
                    this.User_Provided_RatingField = value;
                    this.RaisePropertyChanged("User_Provided_Rating");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RatinDto3", Namespace="http://schemas.datacontract.org/2004/07/OnlineMovieRatingSystem.Model")]
    [System.SerializableAttribute()]
    public partial class RatinDto3 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MovieNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double User_Provided_RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_Rarting_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MovieName {
            get {
                return this.MovieNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieNameField, value) != true)) {
                    this.MovieNameField = value;
                    this.RaisePropertyChanged("MovieName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double User_Provided_Rating {
            get {
                return this.User_Provided_RatingField;
            }
            set {
                if ((this.User_Provided_RatingField.Equals(value) != true)) {
                    this.User_Provided_RatingField = value;
                    this.RaisePropertyChanged("User_Provided_Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Rarting_Id {
            get {
                return this.User_Rarting_IdField;
            }
            set {
                if ((this.User_Rarting_IdField.Equals(value) != true)) {
                    this.User_Rarting_IdField = value;
                    this.RaisePropertyChanged("User_Rarting_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMovieRating")]
    public interface IMovieRating {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/AddMovie", ReplyAction="http://tempuri.org/IMovieRating/AddMovieResponse")]
        string AddMovie(OnlineMovieRatingSystemClient.ServiceReference1.Movie e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/AddMovie", ReplyAction="http://tempuri.org/IMovieRating/AddMovieResponse")]
        System.Threading.Tasks.Task<string> AddMovieAsync(OnlineMovieRatingSystemClient.ServiceReference1.Movie e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/UpdateMovie", ReplyAction="http://tempuri.org/IMovieRating/UpdateMovieResponse")]
        string UpdateMovie(int id, OnlineMovieRatingSystemClient.ServiceReference1.Movie e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/UpdateMovie", ReplyAction="http://tempuri.org/IMovieRating/UpdateMovieResponse")]
        System.Threading.Tasks.Task<string> UpdateMovieAsync(int id, OnlineMovieRatingSystemClient.ServiceReference1.Movie e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/DeleteMovie", ReplyAction="http://tempuri.org/IMovieRating/DeleteMovieResponse")]
        string DeleteMovie(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/DeleteMovie", ReplyAction="http://tempuri.org/IMovieRating/DeleteMovieResponse")]
        System.Threading.Tasks.Task<string> DeleteMovieAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/ShowMovie", ReplyAction="http://tempuri.org/IMovieRating/ShowMovieResponse")]
        OnlineMovieRatingSystemClient.ServiceReference1.Movie[] ShowMovie();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/ShowMovie", ReplyAction="http://tempuri.org/IMovieRating/ShowMovieResponse")]
        System.Threading.Tasks.Task<OnlineMovieRatingSystemClient.ServiceReference1.Movie[]> ShowMovieAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/AddUser", ReplyAction="http://tempuri.org/IMovieRating/AddUserResponse")]
        string AddUser(OnlineMovieRatingSystemClient.ServiceReference1.SystemUser s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/AddUser", ReplyAction="http://tempuri.org/IMovieRating/AddUserResponse")]
        System.Threading.Tasks.Task<string> AddUserAsync(OnlineMovieRatingSystemClient.ServiceReference1.SystemUser s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/DeleteUser", ReplyAction="http://tempuri.org/IMovieRating/DeleteUserResponse")]
        string DeleteUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/DeleteUser", ReplyAction="http://tempuri.org/IMovieRating/DeleteUserResponse")]
        System.Threading.Tasks.Task<string> DeleteUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/UpdateUser", ReplyAction="http://tempuri.org/IMovieRating/UpdateUserResponse")]
        string UpdateUser(int id, OnlineMovieRatingSystemClient.ServiceReference1.SystemUser e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/UpdateUser", ReplyAction="http://tempuri.org/IMovieRating/UpdateUserResponse")]
        System.Threading.Tasks.Task<string> UpdateUserAsync(int id, OnlineMovieRatingSystemClient.ServiceReference1.SystemUser e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/ShowUser", ReplyAction="http://tempuri.org/IMovieRating/ShowUserResponse")]
        OnlineMovieRatingSystemClient.ServiceReference1.SystemUser[] ShowUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/ShowUser", ReplyAction="http://tempuri.org/IMovieRating/ShowUserResponse")]
        System.Threading.Tasks.Task<OnlineMovieRatingSystemClient.ServiceReference1.SystemUser[]> ShowUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/Verify_User", ReplyAction="http://tempuri.org/IMovieRating/Verify_UserResponse")]
        string Verify_User(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/Verify_User", ReplyAction="http://tempuri.org/IMovieRating/Verify_UserResponse")]
        System.Threading.Tasks.Task<string> Verify_UserAsync(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/AddRating", ReplyAction="http://tempuri.org/IMovieRating/AddRatingResponse")]
        string AddRating(OnlineMovieRatingSystemClient.ServiceReference1.User_Rating s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/AddRating", ReplyAction="http://tempuri.org/IMovieRating/AddRatingResponse")]
        System.Threading.Tasks.Task<string> AddRatingAsync(OnlineMovieRatingSystemClient.ServiceReference1.User_Rating s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/DeleteRating", ReplyAction="http://tempuri.org/IMovieRating/DeleteRatingResponse")]
        string DeleteRating(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/DeleteRating", ReplyAction="http://tempuri.org/IMovieRating/DeleteRatingResponse")]
        System.Threading.Tasks.Task<string> DeleteRatingAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/UpdateRating", ReplyAction="http://tempuri.org/IMovieRating/UpdateRatingResponse")]
        string UpdateRating(int id, OnlineMovieRatingSystemClient.ServiceReference1.RatinDto e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/UpdateRating", ReplyAction="http://tempuri.org/IMovieRating/UpdateRatingResponse")]
        System.Threading.Tasks.Task<string> UpdateRatingAsync(int id, OnlineMovieRatingSystemClient.ServiceReference1.RatinDto e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/ShowRating", ReplyAction="http://tempuri.org/IMovieRating/ShowRatingResponse")]
        OnlineMovieRatingSystemClient.ServiceReference1.RatinDto[] ShowRating();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/ShowRating", ReplyAction="http://tempuri.org/IMovieRating/ShowRatingResponse")]
        System.Threading.Tasks.Task<OnlineMovieRatingSystemClient.ServiceReference1.RatinDto[]> ShowRatingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/ShowRating_short", ReplyAction="http://tempuri.org/IMovieRating/ShowRating_shortResponse")]
        OnlineMovieRatingSystemClient.ServiceReference1.RatinDto2[] ShowRating_short();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/ShowRating_short", ReplyAction="http://tempuri.org/IMovieRating/ShowRating_shortResponse")]
        System.Threading.Tasks.Task<OnlineMovieRatingSystemClient.ServiceReference1.RatinDto2[]> ShowRating_shortAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/ShowRating_Persional", ReplyAction="http://tempuri.org/IMovieRating/ShowRating_PersionalResponse")]
        OnlineMovieRatingSystemClient.ServiceReference1.RatinDto2[] ShowRating_Persional(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/ShowRating_Persional", ReplyAction="http://tempuri.org/IMovieRating/ShowRating_PersionalResponse")]
        System.Threading.Tasks.Task<OnlineMovieRatingSystemClient.ServiceReference1.RatinDto2[]> ShowRating_PersionalAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/ShowRating_Log", ReplyAction="http://tempuri.org/IMovieRating/ShowRating_LogResponse")]
        OnlineMovieRatingSystemClient.ServiceReference1.RatinDto3[] ShowRating_Log(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/ShowRating_Log", ReplyAction="http://tempuri.org/IMovieRating/ShowRating_LogResponse")]
        System.Threading.Tasks.Task<OnlineMovieRatingSystemClient.ServiceReference1.RatinDto3[]> ShowRating_LogAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/getMovie_Name", ReplyAction="http://tempuri.org/IMovieRating/getMovie_NameResponse")]
        string[] getMovie_Name();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieRating/getMovie_Name", ReplyAction="http://tempuri.org/IMovieRating/getMovie_NameResponse")]
        System.Threading.Tasks.Task<string[]> getMovie_NameAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMovieRatingChannel : OnlineMovieRatingSystemClient.ServiceReference1.IMovieRating, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MovieRatingClient : System.ServiceModel.ClientBase<OnlineMovieRatingSystemClient.ServiceReference1.IMovieRating>, OnlineMovieRatingSystemClient.ServiceReference1.IMovieRating {
        
        public MovieRatingClient() {
        }
        
        public MovieRatingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MovieRatingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovieRatingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovieRatingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddMovie(OnlineMovieRatingSystemClient.ServiceReference1.Movie e) {
            return base.Channel.AddMovie(e);
        }
        
        public System.Threading.Tasks.Task<string> AddMovieAsync(OnlineMovieRatingSystemClient.ServiceReference1.Movie e) {
            return base.Channel.AddMovieAsync(e);
        }
        
        public string UpdateMovie(int id, OnlineMovieRatingSystemClient.ServiceReference1.Movie e) {
            return base.Channel.UpdateMovie(id, e);
        }
        
        public System.Threading.Tasks.Task<string> UpdateMovieAsync(int id, OnlineMovieRatingSystemClient.ServiceReference1.Movie e) {
            return base.Channel.UpdateMovieAsync(id, e);
        }
        
        public string DeleteMovie(int id) {
            return base.Channel.DeleteMovie(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteMovieAsync(int id) {
            return base.Channel.DeleteMovieAsync(id);
        }
        
        public OnlineMovieRatingSystemClient.ServiceReference1.Movie[] ShowMovie() {
            return base.Channel.ShowMovie();
        }
        
        public System.Threading.Tasks.Task<OnlineMovieRatingSystemClient.ServiceReference1.Movie[]> ShowMovieAsync() {
            return base.Channel.ShowMovieAsync();
        }
        
        public string AddUser(OnlineMovieRatingSystemClient.ServiceReference1.SystemUser s) {
            return base.Channel.AddUser(s);
        }
        
        public System.Threading.Tasks.Task<string> AddUserAsync(OnlineMovieRatingSystemClient.ServiceReference1.SystemUser s) {
            return base.Channel.AddUserAsync(s);
        }
        
        public string DeleteUser(int id) {
            return base.Channel.DeleteUser(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteUserAsync(int id) {
            return base.Channel.DeleteUserAsync(id);
        }
        
        public string UpdateUser(int id, OnlineMovieRatingSystemClient.ServiceReference1.SystemUser e) {
            return base.Channel.UpdateUser(id, e);
        }
        
        public System.Threading.Tasks.Task<string> UpdateUserAsync(int id, OnlineMovieRatingSystemClient.ServiceReference1.SystemUser e) {
            return base.Channel.UpdateUserAsync(id, e);
        }
        
        public OnlineMovieRatingSystemClient.ServiceReference1.SystemUser[] ShowUser() {
            return base.Channel.ShowUser();
        }
        
        public System.Threading.Tasks.Task<OnlineMovieRatingSystemClient.ServiceReference1.SystemUser[]> ShowUserAsync() {
            return base.Channel.ShowUserAsync();
        }
        
        public string Verify_User(string user, string pass) {
            return base.Channel.Verify_User(user, pass);
        }
        
        public System.Threading.Tasks.Task<string> Verify_UserAsync(string user, string pass) {
            return base.Channel.Verify_UserAsync(user, pass);
        }
        
        public string AddRating(OnlineMovieRatingSystemClient.ServiceReference1.User_Rating s) {
            return base.Channel.AddRating(s);
        }
        
        public System.Threading.Tasks.Task<string> AddRatingAsync(OnlineMovieRatingSystemClient.ServiceReference1.User_Rating s) {
            return base.Channel.AddRatingAsync(s);
        }
        
        public string DeleteRating(int id) {
            return base.Channel.DeleteRating(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteRatingAsync(int id) {
            return base.Channel.DeleteRatingAsync(id);
        }
        
        public string UpdateRating(int id, OnlineMovieRatingSystemClient.ServiceReference1.RatinDto e) {
            return base.Channel.UpdateRating(id, e);
        }
        
        public System.Threading.Tasks.Task<string> UpdateRatingAsync(int id, OnlineMovieRatingSystemClient.ServiceReference1.RatinDto e) {
            return base.Channel.UpdateRatingAsync(id, e);
        }
        
        public OnlineMovieRatingSystemClient.ServiceReference1.RatinDto[] ShowRating() {
            return base.Channel.ShowRating();
        }
        
        public System.Threading.Tasks.Task<OnlineMovieRatingSystemClient.ServiceReference1.RatinDto[]> ShowRatingAsync() {
            return base.Channel.ShowRatingAsync();
        }
        
        public OnlineMovieRatingSystemClient.ServiceReference1.RatinDto2[] ShowRating_short() {
            return base.Channel.ShowRating_short();
        }
        
        public System.Threading.Tasks.Task<OnlineMovieRatingSystemClient.ServiceReference1.RatinDto2[]> ShowRating_shortAsync() {
            return base.Channel.ShowRating_shortAsync();
        }
        
        public OnlineMovieRatingSystemClient.ServiceReference1.RatinDto2[] ShowRating_Persional(int id) {
            return base.Channel.ShowRating_Persional(id);
        }
        
        public System.Threading.Tasks.Task<OnlineMovieRatingSystemClient.ServiceReference1.RatinDto2[]> ShowRating_PersionalAsync(int id) {
            return base.Channel.ShowRating_PersionalAsync(id);
        }
        
        public OnlineMovieRatingSystemClient.ServiceReference1.RatinDto3[] ShowRating_Log(int id) {
            return base.Channel.ShowRating_Log(id);
        }
        
        public System.Threading.Tasks.Task<OnlineMovieRatingSystemClient.ServiceReference1.RatinDto3[]> ShowRating_LogAsync(int id) {
            return base.Channel.ShowRating_LogAsync(id);
        }
        
        public string[] getMovie_Name() {
            return base.Channel.getMovie_Name();
        }
        
        public System.Threading.Tasks.Task<string[]> getMovie_NameAsync() {
            return base.Channel.getMovie_NameAsync();
        }
    }
}
